### ISSUE TITLE
Compiling errors on a couple plugins on latest Hercules

### ISSUE THREAD

**Issue by ghost** [AnnieRuru/Release#3]
- marketclone plugin error https://i.imgur.com/ROKC3RR.png
- messagecolor plugin error https://i.imgur.com/ss7CRME.png

**Comment by AnnieRuru** [comment]
marketclone already fixed

messagescolor ... https://annieruru.blogspot.com/2019/02/messagecolor.html
https://github.com/AnnieRuru/Release/blob/master/plugins/messagecolor/messagecolor_0.4.c
done, just missing a AREA flag

@EPuncker
